---
  - name: Add ssh agent line to sudoers
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: SSH_AUTH_SOCK
      line: Defaults env_keep += "SSH_AUTH_SOCK"
  - name: Update /etc/hosts
    template:
      src: templates/hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname }}"
  - name: Disable dynamic motd
    replace:
      path: /etc/pam.d/sshd
      regexp: '^([^#].*pam_motd.*)'
      replace: '#\1'
  - name: Enable passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  - name: Deploy apt packages
    apt:
      update_cache: yes
      name:
        - curl
        - git
        - gpg
        - gpg-agent
        - mtr
        - python3-pip
        - tmux
        - traceroute
        - zsh
        - openjdk-8-jdk-headless
        - iptables-persistent
        - certbot
        - mediainfo
        - libimage-exiftool-perl
