---
- name: Copy systemd template
  template:
    src: "templates/nifi-registry.service.j2"
    dest: "/etc/systemd/system/nifi-registry.service"

- name: Re/Start NiFi Registry
  service:
    name: "nifi-registry.service"
    state: restarted
    daemon_reload: yes
    enabled: yes
